news = [
    { name: 'Jerónimo Siller', sector: 'K1' },
    { name: 'Los Olmos', sector: 'K1' },
    { name: 'Los Pinos 1er Sector', sector: 'K1' },
    { name: 'Los Sauces 2do Sector', sector: 'K1' },
    { name: 'Lucio Blanco 1er Sector', sector: 'K1' },
    { name: 'Lucio Blanco 2do Sector', sector: 'K1' },
    { name: 'Lugar de los Patos', sector: 'K1' },
    { name: 'Plan de Ayala', sector: 'K1' },
    { name: 'Revolución 1er Sector', sector: 'K1' },
    { name: 'Revolución 2do Sector', sector: 'K1' },
    { name: 'Revolución 3er Sector', sector: 'K1' },
    { name: 'Revolución 4to Sector', sector: 'K1' },
    { name: 'Revolución 5to Sector', sector: 'K1' },
    { name: 'San Pedro 400', sector: 'K1' },
    { name: 'Unidad Habitacional San Pedro', sector: 'K1' },
    { name: 'Vista Montaña 1er Sector', sector: 'K1' },
    { name: 'Vista Montaña 2do Sector', sector: 'K1' },
    { name: 'Zona Industrial', sector: 'K1' },
    { name: 'Zona Revolución', sector: 'K1' },
    { name: 'Bosques del Valle 5to Sector', sector: 'K2' },
    { name: 'El Refugio', sector: 'K2' },
    { name: 'Hacienda del Valle', sector: 'K2' },
    { name: 'Hacienda el Rosario', sector: 'K2' },
    { name: 'Hacienda San Agustín', sector: 'K2' },
    { name: 'Jardines Coloniales 1er Sector', sector: 'K2' },
    { name: 'Jardines Coloniales 2do Sector', sector: 'K2' },
    { name: 'Jardines Coloniales 3er Sector', sector: 'K2' },
    { name: 'La Encantada', sector: 'K2' },
    { name: 'La Muralla', sector: 'K2' },
    { name: 'La Ventana', sector: 'K2' },
    { name: 'Las Sendas Galicia', sector: 'K2' },
    { name: 'Las Velas', sector: 'K2' },
    { name: 'Los Sauces 1er Sector', sector: 'K2' },
    { name: 'Lucio Blanco 3er Sector', sector: 'K2' },
    { name: 'Mirador del Campestre', sector: 'K2' },
    { name: 'Palo Blanco', sector: 'K2' },
    { name: 'Prados de la Sierra', sector: 'K2' },
    { name: 'Rincón Colonial', sector: 'K2' },
    { name: 'Rincón de Corregidora', sector: 'K2' },
    { name: 'Rincón de San Francisco', sector: 'K2' },
    { name: 'Santa Elena', sector: 'K2' },
    { name: 'Valle de Vasconcelos', sector: 'K2' },
    { name: 'Valle del Mezquite', sector: 'K2' },
    { name: 'Villa Montaña 1er Sector', sector: 'K2' },
    { name: 'Villa Montaña 2do Sector', sector: 'K2' },
    { name: 'Villas del Pedregal', sector: 'K2' },
    { name: 'Zona la Cima', sector: 'K2' },
    { name: 'Zona los Sauces', sector: 'K2' },
    { name: 'Ampliación Tampiquito', sector: 'K3' },
    { name: 'Balcones del Campestre', sector: 'K3' },
    { name: 'Balcones del Valle', sector: 'K3' },
    { name: 'Barrancas del Pedregal', sector: 'K3' },
    { name: 'Bosques de San Pedro', sector: 'K3' },
    { name: 'Bosques del Valle 1er Sector', sector: 'K3' },
    { name: 'Bosques del Valle 2do Sector', sector: 'K3' },
    { name: 'Bosques del Valle 3er Sector', sector: 'K3' },
    { name: 'Bosques del Valle 4to Sector', sector: 'K3' },
    { name: 'Del Valle Oriente', sector: 'K3' },
    { name: 'Jardines del Valle', sector: 'K3' },
    { name: 'Lomas del Rosario', sector: 'K3' },
    { name: 'Lomas del Valle Sector Convento', sector: 'K3' },
    { name: 'Privada Bosques', sector: 'K3' },
    { name: 'Residencial Sierra del Valle', sector: 'K3' },
    { name: 'Rincón de la Montaña 1er Sector', sector: 'K3' },
    { name: 'Rincón de la Montaña 3er Sector', sector: 'K3' },
    { name: 'Sierra Nevada', sector: 'K3' },
    { name: 'Tampiquito', sector: 'K3' },
    { name: 'Valle de Chipinque', sector: 'K3' },
    { name: 'Villas de Terrasol', sector: 'K3' },
    { name: 'Villas del Valle', sector: 'K3' },
    { name: 'Zona Bosques del Valle', sector: 'K3' },
    { name: 'Calendas', sector: 'K4' },
    { name: 'Cortijo del Valle', sector: 'K4' },
    { name: 'Del Valle Sector Fátima', sector: 'K4' },
    { name: 'El Secreto', sector: 'K4' },
    { name: 'Fátima', sector: 'K4' },
    { name: 'Fuentes del Valle Sector Colinas', sector: 'K4' },
    { name: 'Jardines del Campestre', sector: 'K4' },
    { name: 'La Barranca', sector: 'K4' },
    { name: 'Las Alondras', sector: 'K4' },
    { name: 'Los Amates', sector: 'K4' },
    { name: 'Mirador de Vasconcelos', sector: 'K4' },
    { name: 'Portal de Santa Engracia', sector: 'K4' },
    { name: 'Privada Callejones', sector: 'K4' },
    { name: 'Privada Lomas de San Agustín', sector: 'K4' },
    { name: 'Residencial San Carlos', sector: 'K4' },
    { name: 'Santa Engracia', sector: 'K4' },
    { name: 'Valle de Santa Engracia', sector: 'K4' },
    { name: 'Villas de Santa Engracia', sector: 'K4' },
    { name: 'Vista Real', sector: 'K4' },
    { name: 'Volkswagen', sector: 'K4' },
    { name: 'Zona los Callejones', sector: 'K4' },
    { name: 'Zona Santa Engracia', sector: 'K4' },
    { name: 'Alto Eucalipto', sector: 'K5' },
    { name: 'Antigua Hacienda San Agustín', sector: 'K5' },
    { name: 'Arboleda', sector: 'K5' },
    { name: 'Colinas de San Agustín', sector: 'K5' },
    { name: 'Colorines 1er Sector', sector: 'K5' },
    { name: 'Colorines 2do Sector', sector: 'K5' },
    { name: 'Colorines 3er Sector', sector: 'K5' },
    { name: 'El Santuario', sector: 'K5' },
    { name: 'Hacienda Carrizalejo', sector: 'K5' },
    { name: 'Jardines de San Agustín 1er Sector', sector: 'K5' },
    { name: 'Jardines de San Agustín 2do Sector', sector: 'K5' },
    { name: 'Jardines de San Agustín 3er Sector', sector: 'K5' },
    { name: 'La Joya', sector: 'K5' },
    { name: 'Las Cascadas', sector: 'K5' },
    { name: 'Las Querenzas', sector: 'K5' },
    { name: 'Misión de San Patricio', sector: 'K5' },
    { name: 'Olinalá', sector: 'K5' },
    { name: 'Privada Veredalta', sector: 'K5' },
    { name: 'Residencial Chipinque 3er Sector', sector: 'K5' },
    { name: 'Residencial Chipinque 4to Sector', sector: 'K5' },
    { name: 'San Agustín Campestre', sector: 'K5' },
    { name: 'San Patricio 1er Sector', sector: 'K5' },
    { name: 'San Patricio 2do Sector', sector: 'K5' },
    { name: 'San Patricio 3er Sector', sector: 'K5' },
    { name: 'San Patricio 4to Sector', sector: 'K5' },
    { name: 'Veredalta', sector: 'K5' },
    { name: 'Villa Chipinque', sector: 'K5' },
    { name: 'Villas de Aragón', sector: 'K5' },
    { name: 'Zona la Alianza', sector: 'K5' },
    { name: 'Zona Lomas de San Agustín', sector: 'K5' },
    { name: 'Zona Residencial Chipinque', sector: 'K5' },
    { name: 'Zona San Agustín Campestre', sector: 'K5' },
    { name: 'Ampliación Valle del Mirador', sector: 'K6' },
    { name: 'Balcones de San Agustín', sector: 'K6' },
    { name: 'Cantanas', sector: 'K6' },
    { name: 'Colonial de la Sierra', sector: 'K6' },
    { name: 'Colonial San Agustín', sector: 'K6' },
    { name: 'El Obispo', sector: 'K6' },
    { name: 'Hacienda Palo Blanco', sector: 'K6' },
    { name: 'La Diana', sector: 'K6' },
    { name: 'La Ventura', sector: 'K6' },
    { name: 'Lomas de San Agustín 1er Sector', sector: 'K6' },
    { name: 'Lomas de San Agustín 2do Sector', sector: 'K6' },
    { name: 'Lomas de Tampiquito', sector: 'K6' },
    { name: 'Lomas del Valle', sector: 'K6' },
    { name: 'Los Pinos 2do Sector', sector: 'K6' },
    { name: 'Los Quetzales', sector: 'K6' },
    { name: 'Privanzas Burdeos', sector: 'K6' },
    { name: 'Privanzas Corcega', sector: 'K6' },
    { name: 'Privanzas Fundadores', sector: 'K6' },
    { name: 'Privanzas Marsella', sector: 'K6' },
    { name: 'Privanzas Pamplona', sector: 'K6' },
    { name: 'Privanzas Toledo', sector: 'K6' },
    { name: 'Real del Valle', sector: 'K6' },
    { name: 'Real San Agustín', sector: 'K6' },
    { name: 'Residencial Magenta', sector: 'K6' },
    { name: 'Residencial San Mateo', sector: 'K6' },
    { name: 'Rincón del Campestre', sector: 'K6' },
    { name: 'Santa Cruz', sector: 'K6' },
    { name: 'Valle de San Agustín', sector: 'K6' },
    { name: 'Zona Lomas del Campestre', sector: 'K6' },
    { name: 'Zona San Agustín', sector: 'K6' },
    { name: 'Nemesio García Naranjo', sector: 'K2' },
    { name: 'Ampliación Balcones de San Agustín', sector: 'K6' },
    { name: 'Ampliación Canteras', sector: 'K6' },
    { name: 'Ampliación Lomas del Valle', sector: 'K3' },
    { name: 'Ampliación San Pedro 400', sector: 'K1' },
    { name: 'Arboleda Carrizalejo', sector: 'K5' },
    { name: 'Bilanc', sector: 'K2' },
    { name: 'Bosques de la Sierra 1er Sector', sector: 'K3' },
    { name: 'Bosques de la Sierra 2do Sector', sector: 'K3' },
    { name: 'Bosques de la Sierra 3er Sector', sector: 'K3' },
    { name: 'Bosques de los Arizpe', sector: 'K2' },
    { name: 'Bosques de San Angel Ampiación Palmillas', sector: 'K5' },
    { name: 'Bosques de San Angel Sector Palmillas', sector: 'K5' },
    { name: 'Bosques del Valle Ampliación 5to Sector', sector: 'K3' },
    { name: 'Capistrano', sector: 'K3' },
    { name: 'Casco Urbano', sector: 'K2' },
    { name: 'Cerrada Moralillo', sector: 'K3' },
    { name: 'Codornices Aldama', sector: 'K2' },
    { name: 'Colinas de la Sierra Madre', sector: 'K3' },
    { name: 'Colinas de San Angel', sector: 'K5' },
    { name: 'Colonia Del Valle', sector: 'K4' },
    { name: 'Colorines 4to Sector', sector: 'K5' },
    { name: 'Colorines 5to Sector', sector: 'K5' },
    { name: 'Comercial Alpino Chipinque', sector: 'K5' },
    { name: 'Comercial Gómez Morin', sector: 'K5' },
    { name: 'Condominio Horizontal Azahara', sector: 'K5' },
    { name: 'Condominio Horizontal Galeana', sector: 'K3' },
    { name: 'Condominio Volga 1', sector: 'K4' },
    { name: 'Conjunto Habitacional Bugambilias', sector: 'K4' },
    { name: 'Conjunto Habitacional Renzo', sector: 'K6' },
    { name: 'Corporativo Díaz Ordaz', sector: 'K1' },
    { name: 'Corporativo Prodesa', sector: 'K6' },
    { name: 'Corporativo Santa Engracia 1er Sector', sector: 'K5' },
    { name: 'Corporativo Santa Engracia 2do Sector', sector: 'K5' },
    { name: 'De Las Alondras', sector: 'K5' },
    { name: 'Del Valle Sector Norte', sector: 'K4' },
    { name: 'El Manar', sector: 'K5' },
    { name: 'Fuentes del David', sector: 'K4' },
    { name: 'Galeana 148', sector: 'K3' },
    { name: 'Hacienda Las Campanas (El Rosario)', sector: 'K2' },
    { name: 'Haciendas de la Sierra', sector: 'K6' },
    { name: 'Jesús M. Garza', sector: 'K1' },
    { name: 'Joya de la Corona', sector: 'K5' },
    { name: 'La Cima 1er Sector', sector: 'K2' },
    { name: 'La Cima 2do Sector', sector: 'K2' },
    { name: 'La Cima 3er Sector', sector: 'K2' },
    { name: 'La Cooperativa (Provivienda Popular)', sector: 'K3' },
    { name: 'La Montaña', sector: 'K3' },
    { name: 'La Morita', sector: 'K4' },
    { name: 'Las Calzadas', sector: 'K5' },
    { name: 'Las Codornices', sector: 'K2' },
    { name: 'Las Mariposas', sector: 'K3' },
    { name: 'Las Privanzas 3er Sector 2da Etapa', sector: 'K6' },
    { name: 'Lomas de San Angel', sector: 'K5' },
    { name: 'Lomas del Campestre 1er Sector', sector: 'K6' },
    { name: 'Lomas del Campestre 2do Sector', sector: 'K6' },
    { name: 'Lomas del Convento', sector: 'K3' },
    { name: 'Los Arcangeles', sector: 'K6' },
    { name: 'Los Callejones', sector: 'K4' },
    { name: 'Los Encinos de San Agustín 1er Sector', sector: 'K5' },
    { name: 'Los Encinos de San Agustín 2do Sector', sector: 'K5' },
    { name: 'Los Encinos de San Agustín 5to Sector', sector: 'K5' },
    { name: 'Los Encinos de San Agustín 6to Sector', sector: 'K5' },
    { name: 'Los Encinos de San Agustín 7 Sector', sector: 'K5' },
    { name: 'Los Fresnos', sector: 'K3' },
    { name: 'Los Rincones', sector: 'K2' },
    { name: 'Lugar de los Agaves', sector: 'K2' },
    { name: 'Magnolias', sector: 'K5' },
    { name: 'Mansión del Rosario', sector: 'K2' },
    { name: 'Mesa de la Corona 1er Sector', sector: 'K5' },
    { name: 'Mesa de la Corona 2do Sector', sector: 'K5' },
    { name: 'Mirasierra 1er Sector', sector: 'K2' },
    { name: 'Mirasierra 2do Sector', sector: 'K3' },
    { name: 'Mirasierra 3er Sector', sector: 'K4' },
    { name: 'Mirasierra 4to Sector', sector: 'K5' },
    { name: 'Mirasierra 5to Sector', sector: 'K6' },
    { name: 'Misión del Valle', sector: 'K2' },
    { name: 'Misión del Valle 3er Sector', sector: 'K2' },
    { name: 'Olimpico', sector: 'K3' },
    { name: 'Palo Blanco Sector el Edén', sector: 'K2' },
    { name: 'Parque Corporativo Ucaly', sector: 'K6' },
    { name: 'Pedregal del Valle', sector: 'K2' },
    { name: 'Privada 20 de Noviembre', sector: 'K3' },
    { name: 'Privada Amatista', sector: 'K3' },
    { name: 'Privada Calzada del Valle', sector: 'K4' },
    { name: 'Privada Capellanía', sector: 'K4' },
    { name: 'Privada Cassarosa', sector: 'K2' },
    { name: 'Privada de la Paz', sector: 'K2' },
    { name: 'Privada Doblado', sector: 'K2' },
    { name: 'Privada La Cima (La Cuspide)', sector: 'K2' },
    { name: 'Privada Los Encinos', sector: 'K5' },
    { name: 'Privada Mont Parnasse', sector: 'K5' },
    { name: 'Privada Palo Blanco', sector: 'K2' },
    { name: 'Privada Río Ebro', sector: 'K3' },
    { name: 'Privada Río Lerma', sector: 'K4' },
    { name: 'Privada San Andrés', sector: 'K2' },
    { name: 'Privada San Roberto', sector: 'K6' },
    { name: 'Privada Santa Engracia', sector: 'K4' },
    { name: 'Privada Sierra Madre', sector: 'K3' },
    { name: 'Privada Sierra Nevada', sector: 'K3' },
    { name: 'Privada Treviño', sector: 'K2' },
    { name: 'Privada Versalles', sector: 'K2' },
    { name: 'Privanzas  Alicante', sector: 'K6' },
    { name: 'Privanzas  Martinica', sector: 'K6' },
    { name: 'Privanzas  Mónaco', sector: 'K6' },
    { name: 'Privanzas  Niza', sector: 'K6' },
    { name: 'Privanzas  Venecia', sector: 'K6' },
    { name: 'Privanzas 2do Sector P. Alejandria', sector: 'K6' },
    { name: 'Privanzas 4to Sector 1a Etapa', sector: 'K6' },
    { name: 'Privanzas 4to Sector 2da Etapa', sector: 'K6' },
    { name: 'Punto Central', sector: 'K5' },
    { name: 'Residencial Canteras', sector: 'K6' },
    { name: 'Residencial Carrizalejo', sector: 'K5' },
    { name: 'Residencial Chipinque 1er Sector', sector: 'K5' },
    { name: 'Residencial Chipinque 2do Sector', sector: 'K5' },
    { name: 'Residencial Frida', sector: 'K6' },
    { name: 'Residencial Galeana', sector: 'K3' },
    { name: 'Residencial los Cubos', sector: 'K2' },
    { name: 'Residencial San Agustín 1er Sector', sector: 'K4' },
    { name: 'Residencial San Agustín 2do Sector', sector: 'K4' },
    { name: 'Residencial Santa Barbara (La Cripta)', sector: 'K4' },
    { name: 'Residencial Santa Barbara 1er Sector', sector: 'K6' },
    { name: 'Residencial Santa Barbara 2do Sector', sector: 'K6' },
    { name: 'Residencial Santa Fe', sector: 'K6' },
    { name: 'Residencial Villa Montaña', sector: 'K2' },
    { name: 'Rincón de la Montaña 2do Sector', sector: 'K3' },
    { name: 'Rincón del Carrizalejo', sector: 'K3' },
    { name: 'San Francisco', sector: 'K2' },
    { name: 'San Gabriel', sector: 'K2' },
    { name: 'San José', sector: 'K2' },
    { name: 'San Pedro 400 Ampliación Norte', sector: 'K1' },
    { name: 'Santa Barbara', sector: 'K6' },
    { name: 'Santa Barbara Poniente', sector: 'K6' },
    { name: 'Saqqara', sector: 'K4' },
    { name: 'Turquesa Residencial (Lampazos)', sector: 'K4' },
    { name: 'Valle Campestre', sector: 'K5' },
    { name: 'Valle de San Angel Sector Español', sector: 'K5' },
    { name: 'Valle de San Angel Sector Frances', sector: 'K5' },
    { name: 'Valle de San Angel Sector Jardines', sector: 'K5' },
    { name: 'Valle de San Angel Sector Mexicano', sector: 'K5' },
    { name: 'Valle de San Angel Sector Rincó Frances', sector: 'K5' },
    { name: 'Valle del Seminario 1er Sector', sector: 'K1' },
    { name: 'Valle del Seminario 2do Sector', sector: 'K1' },
    { name: 'Villa Campanario', sector: 'K2' },
    { name: 'Villa del Obispo', sector: 'K1' },
    { name: 'Villa Las Palmas', sector: 'K6' },
    { name: 'Villas de Santa Bárbara', sector: 'K2' },
    { name: 'Vista Montaña 3er Sector', sector: 'K1' },
    { name: 'Zona Alpino', sector: 'K5' },
    { name: 'Zona Antigua Hacienda San Agustín', sector: 'K6' },
    { name: 'Zona Campestre', sector: 'K5' },
    { name: 'Zona Canteras', sector: 'K6' },
    { name: 'Zona Cerro de Las Mitras', sector: 'K1' },
    { name: 'Zona Chipinque', sector: 'K5' },
    { name: 'Zona Clouthier', sector: 'K1' },
    { name: 'Zona Colinas de la Sierra Madre', sector: 'K1' },
    { name: 'Zona de la Sierra Madre', sector: 'K5' },
    { name: 'Zona del Rosario', sector: 'K2' },
    { name: 'Zona del Valle', sector: 'K4' },
    { name: 'Zona el Santuario', sector: 'K5' },
    { name: 'Zona Exhacienda Carrizalejo', sector: 'K5' },
    { name: 'Zona Exhacienda San Agustín', sector: 'K6' },
    { name: 'Zona Fátima', sector: 'K3' },
    { name: 'Zona Fundadores', sector: 'K6' },
    { name: 'Zona Gómez Morin', sector: 'K5' },
    { name: 'Zona Jerónimo Siller', sector: 'K3' },
    { name: 'Zona Joya del Venado', sector: 'K5' },
    { name: 'Zona la Diana', sector: 'K4' },
    { name: 'Zona la Ventana', sector: 'K2' },
    { name: 'Zona Loma Larga Oriente', sector: 'K6' },
    { name: 'Zona Loma Larga Poniente', sector: 'K4' },
    { name: 'Zona Los Sabinos (Parcelación Familiar)', sector: 'K4' },
    { name: 'Zona Mesa de la Corona', sector: 'K5' },
    { name: 'Zona Mirasierra', sector: 'K2' },
    { name: 'Zona Montebello', sector: 'K5' },
    { name: 'Zona Pedregal del Valle', sector: 'K2' },
    { name: 'Zona Privanzas', sector: 'K6' },
    { name: 'Zona Valle de Santa Engracia', sector: 'K4' },
    { name: 'Zona Valle del Mezquite', sector: 'K2' },
    { name: 'Zona Valle Oriente', sector: 'K6' },
    { name: 'Zona Valle Oriente Norte', sector: 'K6' },
    { name: 'Zona Valle Poniente', sector: 'K2' },
    { name: 'Zona Valle San Ángel', sector: 'K5' },
    { name: 'Zona Veredalta', sector: 'K5' },
    { name: 'Fuentes del Valle', sector: 'K4' },
    { name: 'Jardines de Mirasierra', sector: 'K2' },
    { name: 'La Finca', sector: 'K2' },
    { name: 'Las Amapas', sector: 'K4' },
    { name: 'Las Ceibas', sector: 'K6' },
    { name: 'Lázaro Garza Ayala', sector: 'K2' },
    { name: 'Lomas de San Agustín 3er Sector', sector: 'K6' },
    { name: 'Luis Echeverría', sector: 'K1' }
]

news.each do |c|
    suburb = Colonium.new(junta_nom: c[:name], sector: c[:sector], is_active: true)

    if suburb.save
        puts "#{c[:name]} saved!"
    else
        puts "#{c[:name]} failed! <<<<<<<<<<<<<<<<<<<<<<<<<<<<<"
    end
end